### ISSUE TITLE
Arbitrary Command Injection

### ISSUE THREAD

**Issue by xstable** [scravy/node-macaddress#19]
Affected versions of this package are vulnerable to Arbitrary Command Injection. An attacker could inject arbitrary shell commands if the user input can influence the iface argument.

https://snyk.io/vuln/npm:macaddress:20180511

**Comment by zhaparoff** [comment]
https://nodesecurity.io/advisories/654
https://hackerone.com/reports/319467

**Comment by 0xF48** [comment]
not sure but `var iface = os.NetworkInterfaces()` index.js is the one that is used, not lib/xxx. the lib/xxx is used by the library itself which is in index.js

**Comment by zhaparoff** [comment]
iface is passed as a first parameter to the '.one' method in the public API.
And is not sanitized in linux/unix/macos implementations.
Only windows one is safe, since does not pass it to syscalls directly.

**Comment by asifm** [comment]
@zhaparoff (I have no idea what iface is or what it is for.) Are you saying I don't need to worry if I have a Windows machine?

**Comment by jourdanrodrigues** [comment]
Just got this as output when installing my dependencies. Maybe flooding the issue, but I think more cases are always welcome.

https://go.npm.me/audit-guide

https://nodesecurity.io/advisories/654

<img width="580" alt="screen shot 2018-05-16 at 22 18 18" src="https://user-images.githubusercontent.com/6227037/40151722-f7951bee-5957-11e8-86a9-c60f48bad621.png">

**Comment by zhuangya** [comment]
`create-react-app` built projects are also infected.

**Comment by Logikgate** [comment]
Hey everyone, I opened a pull request #18 to resolve this.  It is my understanding that by using execFile instead of exec you avoid command injection because the arguments are not run in a shell environment.  I'd love some input on this though.

**Comment by francoabaroa** [comment]
CC: @Logikgate Awesome!! Thank you! 

Here is another reference:

**https://nodejs.org/api/child_process.html#child_process_child_process_execfile_file_args_options_callback**

_"The child_process.execFile() function is similar to child_process.exec() except that it does not spawn a shell by default. Rather, the specified executable file is spawned directly as a new process making it slightly more efficient than child_process.exec().

The same options as child_process.exec() are supported. Since a shell is not spawned, behaviors such as I/O redirection and file globbing are not supported."_

Thanks again

**Comment by TixieSalander** [comment]
Looks like the maintainer(s) of this project haven't pushed a single commit since 3 years or even be active in the issues/PR lately. 
It doesn't seem like a good omen for the projects who are using it. 

Any alternative in mind?

**Comment by jourdanrodrigues** [comment]
@theotix We should really try contact him: http://www.scravy.de/

**Comment by TixieSalander** [comment]
@jourdanrodrigues Email sent

**Comment by Logikgate** [comment]
I had also reached out when I opened the PR, but since there are PR requests of more than a year old and no new commits to this repo I think we can safely assume it is abandoned.

With that in mind I have published a new npm module based on [our fork](https://github.com/flypapertech/node-macaddress).  This fork will be maintained for security fixes and will be open to feature pull requests from the community.

You can use it with:
`npm install macaddress-secure`
or
`yarn add macaddress-secure`

Also, if you're using yarn you can force your sub-modules to use this package by adding the below to your package.json
`"resolutions": `{`
    "*/**/macaddress": "macaddress-secure^0.2.11"
}`

**Comment by abolajibisiriyu** [comment]
@Logikgate I just tried using your suggestion but i got this error:
`warning Resolution field "macaddress-secure^0.2.11" has an invalid version entry and maybe ignored`

**Comment by transitive-bullshit** [comment]
NPM's support team is very responsive for issues like this; I'm guessing that if @scravy doesn't respond soon, they'll happily add anyone here as a collaborator to the original package given the large number of dependencies.

**Comment by martpie** [comment]
Only @scravy can add collaborators to this repo, not NPM. What npm can do is to attribute the name of the package to someone else.

**Comment by transitive-bullshit** [comment]
@KeitIG agreed; I'm just saying that instead of trying to get hundreds of dependents to move npm packages, we should try to get NPM to add @Logikgate or @theotix as collaborators to the npm package, so they can publish a fix to the original package.

**Comment by epet** [comment]
@transitive-bullshit, wouldn't the admin action need to be here on github and on npm allowing @Logikgate to publish a fixed package? Or are you saying only NPM that would allow @Logikgate to take over the npm package name macaddress?

**Comment by transitive-bullshit** [comment]
@epet the latter

**Comment by scravy** [comment]
I accepted pull #20 and released version `0.2.9`.

Thank you all for having an eye on this package.
