### ISSUE TITLE
not working in android

### ISSUE THREAD

**Issue by mvtcode** [scravy/node-macaddress#6]
i using macaddress and jxcore in android, only show ipv4 address.

**Comment by scravy** [comment]
A macaddress is not an ip address.

What is the output you are expecting and what is it that you are getting?

**Comment by scravy** [comment]
Since this report is 4 years old and I have not heard any similar complaints, I am going to close this.

Should this problem persist and you're still interested in this, please tell me about the versions of macaddress, jxcore, and the api you used (`one()` vs `all()`), as well as the android version (or simulator).
